[package]
name = "inflatox"
version = "0.1.0"
edition = "2021"

[lib]
name = "libinflx_rs"
crate_type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { version = "0.15", features = ['rayon'] }
ndarray-linalg = { version = "0.16", features = ['openblas-system'] }
pyo3 = { version = "0.19.0", features = ["extension-module"] }
num-traits = "0.2"
rayon = "1"
libloading = "0.8"

[build]
rustflags = [
  "-C", "link-arg=-lm"
]