[package]
name = "inflatox"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15"
ndarray-linalg = { version = "0.16", features = ['openblas-system'] }
num-traits = "0.2"
libloading = "0.8"

[build-dependencies]
bindgen = "0.65"